[package]
name = "dogpaddle-flow"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"

[dependencies]
dogpaddle-operation.workspace = true
dogpaddle-store.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
