version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /system-tests/debezium-postgres/host
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      d1-host-rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: /crates/debezium/bridge
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /system-tests/debezium-runtime/probe
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
