[package]
name = "dogpaddle-operation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
autotests = false
autobenches = false
autoexamples = false

[lib]
bench = false

[dependencies]
arrow-array.workspace = true
arrow-schema.workspace = true
arrow-select.workspace = true
base64.workspace = true
blake3.workspace = true
chrono.workspace = true
datafusion-common.workspace = true
datafusion-expr.workspace = true
datafusion-physical-expr.workspace = true
datafusion-proto.workspace = true
dogpaddle-change.workspace = true
dogpaddle-debezium.workspace = true
dogpaddle-store.workspace = true
mysql.workspace = true
postgres.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true

[dev-dependencies]
criterion.workspace = true
dogpaddle-perf-context.workspace = true
tempfile.workspace = true

[[bench]]
name = "aggregate_extrema"
harness = false
test = true

[[test]]
name = "correctness"
path = "tests/correctness.rs"

[[example]]
name = "queue_scan"
path = "examples/queue_scan.rs"

[lints]
workspace = true
