[package]
name = "dogpaddle-operation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
autotests = false
autobenches = false

[lib]
bench = false

[dependencies]
arrow-array.workspace = true
arrow-schema.workspace = true
dogpaddle-change.workspace = true
dogpaddle-store.workspace = true
thiserror.workspace = true

[dev-dependencies]
dogpaddle-bench-protocol.workspace = true
tempfile.workspace = true

[[test]]
name = "correctness"
path = "tests/correctness.rs"

[[bench]]
name = "operation_core"
path = "benches/operation_core.rs"
harness = false
test = false

[lints]
workspace = true
