[package]
name = "dogpaddle-data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"

[dependencies]
arrow-array.workspace = true
arrow-ipc.workspace = true
arrow-schema.workspace = true
thiserror.workspace = true

[dev-dependencies]
dogpaddle-store.workspace = true
flatbuffers.workspace = true
tempfile.workspace = true

[lints]
workspace = true
