[package]
name = "dogpaddle-bench-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
autotests = false
autobenches = false

[lib]
bench = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
