/// The semantic difference pattern generated by a workload.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum DiffModel {
    /// Every event adds positive relation weight and never retracts.
    InsertOnly,
    /// Insertions and retractions are generated from a checked relation model.
    ValidChurn,
}

impl DiffModel {
    /// Returns the stable machine-readable model name.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::InsertOnly => "insert_only",
            Self::ValidChurn => "valid_churn",
        }
    }
}

/// A stable synthetic Change workload family.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum WorkloadPersona {
    /// No logical columns; isolates the physical diff and IPC framing.
    DiffOnlyControl,
    /// A 16-column layout spanning every currently supported Arrow layout.
    LayoutV1_16,
    /// Eight fixed-width event columns.
    FixedEvent8,
    /// Sixteen mixed fixed/variable-width and nullable event columns.
    MixedEvent16,
    /// Sixty-four non-null numeric columns.
    WideNumeric64,
    /// Four columns dominated by one configurable Binary payload.
    BlobEvent4,
    /// Eight top-level columns containing List and Struct subtrees.
    NestedEvent8,
    /// A non-zero-offset slice of the sixteen-column mixed layout.
    SlicedMixed16,
    /// A deterministic rotation through all concrete personas.
    Heterogeneous,
}

impl WorkloadPersona {
    /// Every workload persona in stable reporting order.
    pub const ALL: [Self; 9] = [
        Self::DiffOnlyControl,
        Self::LayoutV1_16,
        Self::FixedEvent8,
        Self::MixedEvent16,
        Self::WideNumeric64,
        Self::BlobEvent4,
        Self::NestedEvent8,
        Self::SlicedMixed16,
        Self::Heterogeneous,
    ];

    /// Returns the stable machine-readable persona name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        self.descriptor().name
    }

    /// Returns the stable descriptor for this persona.
    #[must_use]
    pub const fn descriptor(self) -> &'static WorkloadDescriptor {
        match self {
            Self::DiffOnlyControl => &DIFF_ONLY_DESCRIPTOR,
            Self::LayoutV1_16 => &LAYOUT_V1_DESCRIPTOR,
            Self::FixedEvent8 => &FIXED_EVENT_DESCRIPTOR,
            Self::MixedEvent16 => &MIXED_EVENT_DESCRIPTOR,
            Self::WideNumeric64 => &WIDE_NUMERIC_DESCRIPTOR,
            Self::BlobEvent4 => &BLOB_EVENT_DESCRIPTOR,
            Self::NestedEvent8 => &NESTED_EVENT_DESCRIPTOR,
            Self::SlicedMixed16 => &SLICED_MIXED_DESCRIPTOR,
            Self::Heterogeneous => &HETEROGENEOUS_DESCRIPTOR,
        }
    }

    /// Resolves the concrete persona used at `ordinal`.
    #[must_use]
    pub const fn concrete_at(self, ordinal: usize) -> Self {
        if matches!(self, Self::Heterogeneous) {
            HETEROGENEOUS_ROTATION[ordinal % HETEROGENEOUS_ROTATION.len()]
        } else {
            self
        }
    }

    /// Returns the selected logical field indices for a legal profile.
    #[must_use]
    pub fn projection_indices(self, profile: ProjectionProfile) -> Option<&'static [usize]> {
        let descriptor = self.descriptor();
        if descriptor.schemas.len() != 1 {
            return None;
        }
        descriptor.schemas[0].projection(profile)
    }
}

/// A projection shape shared by correctness and performance protocols.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ProjectionProfile {
    /// Select no business fields; the diff remains implicit.
    DiffOnly,
    /// Select only the event key.
    KeyOnly,
    /// Select a small, potentially non-adjacent subset.
    Sparse,
    /// Select most business fields while omitting the primary wide payload.
    Dense,
    /// Select only the primary variable-width payload.
    PayloadOnly,
    /// Select every business field through the projected decoder.
    Identity,
}

impl ProjectionProfile {
    /// Every projection profile in stable reporting order.
    pub const ALL: [Self; 6] = [
        Self::DiffOnly,
        Self::KeyOnly,
        Self::Sparse,
        Self::Dense,
        Self::PayloadOnly,
        Self::Identity,
    ];

    /// Returns the stable machine-readable profile name.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::DiffOnly => "diff_only",
            Self::KeyOnly => "key_only",
            Self::Sparse => "sparse",
            Self::Dense => "dense",
            Self::PayloadOnly => "payload_only",
            Self::Identity => "identity",
        }
    }
}

/// One legal projection for a concrete Schema descriptor.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ProjectionDescriptor {
    /// Semantic projection profile.
    pub profile: ProjectionProfile,
    /// Strictly increasing top-level logical field indices.
    pub selected_columns: &'static [usize],
}

/// Structural facts about one concrete logical Schema.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SchemaDescriptor {
    /// Stable Schema shape name.
    pub name: &'static str,
    /// Top-level business columns, excluding the physical diff.
    pub business_columns: usize,
    /// Physical top-level columns, including the leading diff.
    pub physical_columns: usize,
    /// Logical leaf fields after recursively expanding List and Struct nodes.
    pub leaf_columns: usize,
    /// Nullable top-level business fields.
    pub top_level_nullable_columns: usize,
    /// Top-level Utf8 or Binary business fields.
    pub top_level_variable_width_columns: usize,
    /// Top-level List or Struct business fields.
    pub top_level_nested_columns: usize,
    /// Nullable logical fields across the complete field tree.
    pub total_nullable_fields: usize,
    /// Utf8 or Binary leaf fields across the complete field tree.
    pub variable_width_leaf_columns: usize,
    /// List or Struct nodes across the complete field tree.
    pub total_nested_fields: usize,
    /// Stable compact description of the logical field types.
    pub type_summary: &'static str,
    /// Legal projection profiles for this exact Schema.
    pub projection_profiles: &'static [ProjectionDescriptor],
}

impl SchemaDescriptor {
    /// Returns the selected indices for `profile`, if the profile is legal.
    #[must_use]
    pub fn projection(self, profile: ProjectionProfile) -> Option<&'static [usize]> {
        self.projection_profiles
            .iter()
            .find(|descriptor| descriptor.profile == profile)
            .map(|descriptor| descriptor.selected_columns)
    }
}

/// Stable metadata for a workload persona.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WorkloadDescriptor {
    /// Stable workload name.
    pub name: &'static str,
    /// Difference model generated by this workload.
    pub diff_model: DiffModel,
    /// Concrete Schemas used by this persona. Heterogeneous workloads expose
    /// every Schema in their deterministic rotation.
    pub schemas: &'static [SchemaDescriptor],
}

const DIFF_PROJECTIONS: &[ProjectionDescriptor] = &[
    ProjectionDescriptor {
        profile: ProjectionProfile::DiffOnly,
        selected_columns: &[],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Identity,
        selected_columns: &[],
    },
];
const FIXED_PROJECTIONS: &[ProjectionDescriptor] = &[
    ProjectionDescriptor {
        profile: ProjectionProfile::DiffOnly,
        selected_columns: &[],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::KeyOnly,
        selected_columns: &[0],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Sparse,
        selected_columns: &[0, 7],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Dense,
        selected_columns: &[0, 1, 2, 3, 4, 5, 6],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Identity,
        selected_columns: &[0, 1, 2, 3, 4, 5, 6, 7],
    },
];
const MIXED_PROJECTIONS: &[ProjectionDescriptor] = &[
    ProjectionDescriptor {
        profile: ProjectionProfile::DiffOnly,
        selected_columns: &[],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::KeyOnly,
        selected_columns: &[0],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Sparse,
        selected_columns: &[0, 5, 15],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Dense,
        selected_columns: &[0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::PayloadOnly,
        selected_columns: &[7],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Identity,
        selected_columns: &[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
];
const WIDE_PROJECTIONS: &[ProjectionDescriptor] = &[
    ProjectionDescriptor {
        profile: ProjectionProfile::DiffOnly,
        selected_columns: &[],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::KeyOnly,
        selected_columns: &[0],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Sparse,
        selected_columns: &[0, 31, 63],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Dense,
        selected_columns: &WIDE_DENSE,
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Identity,
        selected_columns: &WIDE_IDENTITY,
    },
];
const BLOB_PROJECTIONS: &[ProjectionDescriptor] = &[
    ProjectionDescriptor {
        profile: ProjectionProfile::DiffOnly,
        selected_columns: &[],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::KeyOnly,
        selected_columns: &[0],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Sparse,
        selected_columns: &[0, 3],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Dense,
        selected_columns: &[0, 1, 3],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::PayloadOnly,
        selected_columns: &[2],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Identity,
        selected_columns: &[0, 1, 2, 3],
    },
];
const NESTED_PROJECTIONS: &[ProjectionDescriptor] = &[
    ProjectionDescriptor {
        profile: ProjectionProfile::DiffOnly,
        selected_columns: &[],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::KeyOnly,
        selected_columns: &[0],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Sparse,
        selected_columns: &[0, 4, 5],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Dense,
        selected_columns: &[0, 1, 2, 4, 5, 6, 7],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::PayloadOnly,
        selected_columns: &[3],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Identity,
        selected_columns: &[0, 1, 2, 3, 4, 5, 6, 7],
    },
];
const LAYOUT_PROJECTIONS: &[ProjectionDescriptor] = &[
    ProjectionDescriptor {
        profile: ProjectionProfile::DiffOnly,
        selected_columns: &[],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::KeyOnly,
        selected_columns: &[0],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Sparse,
        selected_columns: &[0, 11, 15],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Dense,
        selected_columns: &[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::PayloadOnly,
        selected_columns: &[12],
    },
    ProjectionDescriptor {
        profile: ProjectionProfile::Identity,
        selected_columns: &[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
];

const WIDE_IDENTITY: [usize; 64] = make_indices::<64>();
const WIDE_DENSE: [usize; 63] = make_indices::<63>();

const fn make_indices<const N: usize>() -> [usize; N] {
    let mut values = [0; N];
    let mut index = 0;
    while index < N {
        values[index] = index;
        index += 1;
    }
    values
}

const DIFF_SCHEMA: SchemaDescriptor = SchemaDescriptor {
    name: "diff_only_control",
    business_columns: 0,
    physical_columns: 1,
    leaf_columns: 0,
    top_level_nullable_columns: 0,
    top_level_variable_width_columns: 0,
    top_level_nested_columns: 0,
    total_nullable_fields: 0,
    variable_width_leaf_columns: 0,
    total_nested_fields: 0,
    type_summary: "[]",
    projection_profiles: DIFF_PROJECTIONS,
};
const LAYOUT_SCHEMA: SchemaDescriptor = SchemaDescriptor {
    name: "layout_v1_16",
    business_columns: 16,
    physical_columns: 17,
    leaf_columns: 17,
    top_level_nullable_columns: 6,
    top_level_variable_width_columns: 2,
    top_level_nested_columns: 2,
    total_nullable_fields: 8,
    variable_width_leaf_columns: 3,
    total_nested_fields: 2,
    type_summary: "u64,bool,i8,u8,i16,u16,i32,u32,f32,i64,f64,utf8,binary,null,list<i64>,struct<u64,utf8>",
    projection_profiles: LAYOUT_PROJECTIONS,
};
const FIXED_SCHEMA: SchemaDescriptor = SchemaDescriptor {
    name: "fixed_event_8",
    business_columns: 8,
    physical_columns: 9,
    leaf_columns: 8,
    top_level_nullable_columns: 0,
    top_level_variable_width_columns: 0,
    top_level_nested_columns: 0,
    total_nullable_fields: 0,
    variable_width_leaf_columns: 0,
    total_nested_fields: 0,
    type_summary: "u64,u64,i64,u32,u16,i32,f64,bool",
    projection_profiles: FIXED_PROJECTIONS,
};
const MIXED_SCHEMA: SchemaDescriptor = SchemaDescriptor {
    name: "mixed_event_16",
    business_columns: 16,
    physical_columns: 17,
    leaf_columns: 16,
    top_level_nullable_columns: 9,
    top_level_variable_width_columns: 4,
    top_level_nested_columns: 0,
    total_nullable_fields: 9,
    variable_width_leaf_columns: 4,
    total_nested_fields: 0,
    type_summary: "u64,u64,bool?,i32?,f64?,utf8?,utf8,binary?,binary,i64,u32,i16?,f32?,bool,null,u64?",
    projection_profiles: MIXED_PROJECTIONS,
};
const WIDE_SCHEMA: SchemaDescriptor = SchemaDescriptor {
    name: "wide_numeric_64",
    business_columns: 64,
    physical_columns: 65,
    leaf_columns: 64,
    top_level_nullable_columns: 0,
    top_level_variable_width_columns: 0,
    top_level_nested_columns: 0,
    total_nullable_fields: 0,
    variable_width_leaf_columns: 0,
    total_nested_fields: 0,
    type_summary: "64xu64",
    projection_profiles: WIDE_PROJECTIONS,
};
const BLOB_SCHEMA: SchemaDescriptor = SchemaDescriptor {
    name: "blob_event_4",
    business_columns: 4,
    physical_columns: 5,
    leaf_columns: 4,
    top_level_nullable_columns: 0,
    top_level_variable_width_columns: 1,
    top_level_nested_columns: 0,
    total_nullable_fields: 0,
    variable_width_leaf_columns: 1,
    total_nested_fields: 0,
    type_summary: "u64,u32,binary,u64",
    projection_profiles: BLOB_PROJECTIONS,
};
const NESTED_SCHEMA: SchemaDescriptor = SchemaDescriptor {
    name: "nested_event_8",
    business_columns: 8,
    physical_columns: 9,
    leaf_columns: 9,
    top_level_nullable_columns: 6,
    top_level_variable_width_columns: 3,
    top_level_nested_columns: 2,
    total_nullable_fields: 8,
    variable_width_leaf_columns: 4,
    total_nested_fields: 2,
    type_summary: "u64,u64,utf8?,binary?,list<i64>?,struct<u64,utf8?>?,bool?,utf8?",
    projection_profiles: NESTED_PROJECTIONS,
};
const SLICED_SCHEMA: SchemaDescriptor = SchemaDescriptor {
    name: "sliced_mixed_16",
    ..MIXED_SCHEMA
};

const DIFF_ONLY_DESCRIPTOR: WorkloadDescriptor = WorkloadDescriptor {
    name: "diff_only_control",
    diff_model: DiffModel::InsertOnly,
    schemas: &[DIFF_SCHEMA],
};
const LAYOUT_V1_DESCRIPTOR: WorkloadDescriptor = WorkloadDescriptor {
    name: "layout_v1_16",
    diff_model: DiffModel::InsertOnly,
    schemas: &[LAYOUT_SCHEMA],
};
const FIXED_EVENT_DESCRIPTOR: WorkloadDescriptor = WorkloadDescriptor {
    name: "fixed_event_8",
    diff_model: DiffModel::InsertOnly,
    schemas: &[FIXED_SCHEMA],
};
const MIXED_EVENT_DESCRIPTOR: WorkloadDescriptor = WorkloadDescriptor {
    name: "mixed_event_16",
    diff_model: DiffModel::InsertOnly,
    schemas: &[MIXED_SCHEMA],
};
const WIDE_NUMERIC_DESCRIPTOR: WorkloadDescriptor = WorkloadDescriptor {
    name: "wide_numeric_64",
    diff_model: DiffModel::InsertOnly,
    schemas: &[WIDE_SCHEMA],
};
const BLOB_EVENT_DESCRIPTOR: WorkloadDescriptor = WorkloadDescriptor {
    name: "blob_event_4",
    diff_model: DiffModel::InsertOnly,
    schemas: &[BLOB_SCHEMA],
};
const NESTED_EVENT_DESCRIPTOR: WorkloadDescriptor = WorkloadDescriptor {
    name: "nested_event_8",
    diff_model: DiffModel::InsertOnly,
    schemas: &[NESTED_SCHEMA],
};
const SLICED_MIXED_DESCRIPTOR: WorkloadDescriptor = WorkloadDescriptor {
    name: "sliced_mixed_16",
    diff_model: DiffModel::InsertOnly,
    schemas: &[SLICED_SCHEMA],
};
const HETEROGENEOUS_DESCRIPTOR: WorkloadDescriptor = WorkloadDescriptor {
    name: "heterogeneous",
    diff_model: DiffModel::InsertOnly,
    schemas: &[
        DIFF_SCHEMA,
        LAYOUT_SCHEMA,
        FIXED_SCHEMA,
        MIXED_SCHEMA,
        WIDE_SCHEMA,
        BLOB_SCHEMA,
        NESTED_SCHEMA,
        SLICED_SCHEMA,
    ],
};
const HETEROGENEOUS_ROTATION: [WorkloadPersona; 8] = [
    WorkloadPersona::DiffOnlyControl,
    WorkloadPersona::LayoutV1_16,
    WorkloadPersona::FixedEvent8,
    WorkloadPersona::MixedEvent16,
    WorkloadPersona::WideNumeric64,
    WorkloadPersona::BlobEvent4,
    WorkloadPersona::NestedEvent8,
    WorkloadPersona::SlicedMixed16,
];
