[package]
name = "dogpaddle-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"

[dependencies]
libmdbx.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bench]]
name = "ordered_map"
harness = false
test = false

[[bench]]
name = "cell"
harness = false
test = false

[[bench]]
name = "append_log"
harness = false
test = false

[[bench]]
name = "append_log_endurance"
harness = false
test = false

[lints]
workspace = true
