[package]
name = "dogpaddle-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
libmdbx.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bench]]
name = "store"
harness = false
test = false

[lints]
workspace = true
