use std::{
    any::Any, collections::BTreeMap, error::Error, fmt::Debug, marker::PhantomData, num::NonZeroU32,
};

use arrow_schema::SchemaRef;
use dogpaddle_change::{SchemaError, validate_schema};
use dogpaddle_store::{Store, StoreData, StoreError};
use thiserror::Error;

use crate::operation::Operation;

mod private {
    use arrow_schema::SchemaRef;

    use super::{OperationBinding, OperationSchemaError};

    pub trait Sealed {
        fn bind_schemas(
            &self,
            input_schemas: &[SchemaRef],
        ) -> Result<OperationBinding, OperationSchemaError>;
    }
}

pub(crate) use private::Sealed;

type ErasedData = Box<dyn Any + Send + Sync>;
type CreateFn = fn(&mut Store, &str) -> Result<ErasedData, StoreError>;
type OpenFn = fn(&Store, &str) -> Result<ErasedData, StoreError>;
type MaterializeFn = Box<
    dyn FnOnce(&mut DataInstances) -> Result<Box<dyn Operation>, MaterializeError> + Send + 'static,
>;

/// Type-erased Schema rejection from one concrete Operation definition.
///
/// Concrete definitions retain their own structured error types. Flow adds
/// Station identity without enumerating Operation-specific Schema rules.
pub type OperationSchemaError = Box<dyn Error + Send + Sync + 'static>;

/// One pure, ephemeral binding of an Operation definition to exact input Schemas.
///
/// A binding owns the exact output Schema and any concrete compiled information
/// needed by the runtime Operation. It remains Store-unbound until Flow injects
/// the definition's declared data instances through [`Self::materialize`].
/// Bindings are neither persisted nor retained by a running Flow.
#[doc(hidden)]
pub struct OperationBinding {
    output_schema: Option<SchemaRef>,
    materialize: MaterializeFn,
}

/// One stable logical data name paired with its erased typed data class.
///
/// Concrete operation modules declare these values statically. Flow calls the
/// embedded typed `create` or `open` function without enumerating operations or
/// Store collection types.
#[doc(hidden)]
#[derive(Clone, Copy)]
pub struct DataDeclaration {
    name: &'static str,
    create: CreateFn,
    open: OpenFn,
}

/// Named typed data objects created or opened by Flow for one Operation binding.
///
/// Values are erased only while crossing the object-safe binding boundary. A
/// concrete binding consumes them with the typed names generated by its
/// definition's declaration, and the runtime Operation stores only execution
/// parameters and concrete collections rather than retaining the definition or
/// binding.
#[doc(hidden)]
pub struct DataInstances {
    remaining: BTreeMap<&'static str, ErasedData>,
}

/// One typed logical data name used by a concrete definition.
pub(crate) struct DataName<D> {
    declaration: DataDeclaration,
    _data: PhantomData<fn() -> D>,
}

/// Complete structural kind explicitly declared by an Operation definition.
///
/// The kind combines the Operation's nominal role with its input arity so that
/// a source cannot declare inputs and an input-consuming Operation cannot
/// declare zero inputs. It is supplied by the concrete Operation rather than
/// inferred from topology position.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum OperationKind {
    /// Produces records without consuming upstream input.
    Source,
    /// Consumes upstream records and produces downstream records.
    Transform(NonZeroU32),
    /// Consumes upstream records without producing downstream output.
    Sink(NonZeroU32),
}

impl OperationKind {
    /// Returns the exact number of ordered upstream inputs.
    #[must_use]
    pub const fn input_count(self) -> u32 {
        match self {
            Self::Source => 0,
            Self::Transform(count) | Self::Sink(count) => count.get(),
        }
    }

    /// Returns whether this kind is a source.
    #[must_use]
    pub const fn is_source(self) -> bool {
        matches!(self, Self::Source)
    }

    /// Returns whether this kind is a sink.
    #[must_use]
    pub const fn is_sink(self) -> bool {
        matches!(self, Self::Sink(_))
    }

    /// Returns whether this kind owns a downstream output stream.
    #[must_use]
    pub const fn has_output(self) -> bool {
        matches!(self, Self::Source | Self::Transform(_))
    }
}

/// Pure definition shared by every built-in operation.
///
/// The trait is sealed: the persistent operation set is closed inside this
/// crate. Flow first uses the final binding entrypoint on the trait object,
/// then creates or opens the declared data objects and consumes that binding
/// to assemble its runtime [`Operation`].
pub trait OperationDefinition: private::Sealed + Debug + Send + Sync + 'static {
    /// Returns the Operation's explicitly declared structural kind and input arity.
    fn kind(&self) -> OperationKind;

    /// Returns the operation's stable logical data names and typed classes.
    ///
    /// Flow prefixes each name with the owning station's stable resource path.
    /// Names, collection types, codecs, and any applicable size choices form
    /// part of the operation's persistent schema. The returned slice has
    /// deterministic declaration order, while materialization binds instances
    /// by name.
    #[doc(hidden)]
    fn data(&self) -> &'static [DataDeclaration];

    /// Returns this definition's stable persistent tag.
    #[doc(hidden)]
    fn persistence_tag(&self) -> u16;

    /// Appends this definition's variant-specific persistent payload.
    #[doc(hidden)]
    fn encode_payload(&self, output: &mut Vec<u8>);
}

impl dyn OperationDefinition + '_ {
    /// Purely binds this definition to ordered, exact logical input Schemas.
    ///
    /// A successful binding validates all input-specific rules, fixes the
    /// Operation's exact output Schema when it has one, and owns any compiled
    /// Schema-dependent execution information. The input slice is ordered by
    /// the Definition's zero-based ports. Source definitions receive an empty
    /// slice.
    ///
    /// The binding may depend only on the persistent Definition and supplied
    /// Schemas. It must not access Store, external registries, time, randomness,
    /// or runtime data. The same persistent tag, payload, and ordered input
    /// Schemas must retain the same binding semantics.
    ///
    /// # Errors
    ///
    /// Returns [`OperationBindError`] when the input count is wrong, an input or
    /// output Schema is not a valid `DogPaddle` logical Schema, the concrete
    /// Operation rejects the inputs, or its output presence contradicts
    /// [`OperationDefinition::kind`].
    ///
    /// # Panics
    ///
    /// Panics on a target whose `usize` cannot represent a `u32` input count.
    /// `DogPaddle`'s supported Arrow targets satisfy this requirement.
    pub fn bind(
        &self,
        input_schemas: &[SchemaRef],
    ) -> Result<OperationBinding, OperationBindError> {
        let kind = self.kind();
        let expected =
            usize::try_from(kind.input_count()).expect("an Operation input count fits usize");
        let actual = input_schemas.len();
        if actual != expected {
            return Err(OperationBindError::InputCount { expected, actual });
        }
        for (input, schema) in input_schemas.iter().enumerate() {
            validate_schema(schema)
                .map_err(|source| OperationBindError::InvalidInputSchema { input, source })?;
        }

        let binding = private::Sealed::bind_schemas(self, input_schemas)
            .map_err(|source| OperationBindError::Rejected { source })?;
        match (kind.has_output(), binding.output_schema.as_ref()) {
            (true, None) => return Err(OperationBindError::MissingOutput),
            (false, Some(_)) => return Err(OperationBindError::UnexpectedOutput),
            (true, Some(schema)) => {
                validate_schema(schema)
                    .map_err(|source| OperationBindError::InvalidOutputSchema { source })?;
            }
            (false, None) => {}
        }
        Ok(binding)
    }
}

impl OperationBinding {
    pub(crate) fn new<F>(output_schema: Option<SchemaRef>, materialize: F) -> Self
    where
        F: FnOnce(&mut DataInstances) -> Result<Box<dyn Operation>, MaterializeError>
            + Send
            + 'static,
    {
        Self {
            output_schema,
            materialize: Box::new(materialize),
        }
    }

    /// Returns the exact logical output Schema, or `None` for a Sink binding.
    #[doc(hidden)]
    #[must_use]
    pub const fn output_schema(&self) -> Option<&SchemaRef> {
        self.output_schema.as_ref()
    }

    /// Consumes this binding and its named typed data instances.
    ///
    /// # Errors
    ///
    /// Returns [`MaterializeError`] when the supplied instances are missing,
    /// have the wrong class, or remain unconsumed after assembly.
    #[doc(hidden)]
    pub fn materialize(
        self,
        mut data: DataInstances,
    ) -> Result<Box<dyn Operation>, MaterializeError> {
        let operation = (self.materialize)(&mut data)?;
        data.finish()?;
        Ok(operation)
    }

    pub(crate) fn without_data<O>(output_schema: Option<SchemaRef>, operation: O) -> Self
    where
        O: Operation,
    {
        Self::new(output_schema, move |_data| Ok(Box::new(operation)))
    }
}

impl DataDeclaration {
    /// Returns the stable logical resource name.
    #[doc(hidden)]
    #[must_use]
    pub const fn name(&self) -> &'static str {
        self.name
    }

    /// Creates this declaration's concrete data object.
    ///
    /// # Errors
    ///
    /// Returns a Store error when the physical resource cannot be created.
    #[doc(hidden)]
    pub fn create(
        &self,
        store: &mut Store,
        physical_name: &str,
    ) -> Result<DataInstance, StoreError> {
        (self.create)(store, physical_name).map(|data| DataInstance {
            name: self.name,
            data,
        })
    }

    /// Opens this declaration's concrete data object.
    ///
    /// # Errors
    ///
    /// Returns a Store error when the physical resource is missing, has the
    /// wrong placement, or cannot be opened.
    #[doc(hidden)]
    pub fn open(&self, store: &Store, physical_name: &str) -> Result<DataInstance, StoreError> {
        (self.open)(store, physical_name).map(|data| DataInstance {
            name: self.name,
            data,
        })
    }
}

/// One erased data instance carrying its stable logical name.
#[doc(hidden)]
pub struct DataInstance {
    name: &'static str,
    data: ErasedData,
}

impl DataInstances {
    /// Creates an empty instance map.
    #[doc(hidden)]
    #[must_use]
    pub const fn new() -> Self {
        Self {
            remaining: BTreeMap::new(),
        }
    }

    /// Adds one data object created or opened from a declaration.
    ///
    /// # Errors
    ///
    /// Returns [`MaterializeError::DuplicateData`] when the name is already present.
    #[doc(hidden)]
    pub fn insert(&mut self, instance: DataInstance) -> Result<(), MaterializeError> {
        if self.remaining.contains_key(instance.name) {
            return Err(MaterializeError::DuplicateData {
                name: instance.name,
            });
        }
        self.remaining.insert(instance.name, instance.data);
        Ok(())
    }

    /// Verifies that the operation consumed every provided instance.
    ///
    /// # Errors
    ///
    /// Returns [`MaterializeError::UnexpectedData`] for the first unconsumed name.
    pub(crate) fn finish(self) -> Result<(), MaterializeError> {
        self.remaining.into_keys().next().map_or(Ok(()), |name| {
            Err(MaterializeError::UnexpectedData { name })
        })
    }

    pub(crate) fn take<D>(&mut self, name: &DataName<D>) -> Result<D, MaterializeError>
    where
        D: StoreData + Send + Sync + 'static,
    {
        let logical_name = name.declaration.name;
        let erased = self
            .remaining
            .remove(logical_name)
            .ok_or(MaterializeError::MissingData { name: logical_name })?;
        erased
            .downcast::<D>()
            .map(|data| *data)
            .map_err(|_| MaterializeError::WrongDataClass { name: logical_name })
    }
}

impl<D> DataName<D>
where
    D: StoreData + Send + Sync + 'static,
{
    pub(crate) const fn new(name: &'static str) -> Self {
        Self {
            declaration: DataDeclaration {
                name,
                create: create::<D>,
                open: open::<D>,
            },
            _data: PhantomData,
        }
    }

    pub(crate) const fn declaration(&self) -> DataDeclaration {
        self.declaration
    }
}

fn create<D>(store: &mut Store, name: &str) -> Result<ErasedData, StoreError>
where
    D: StoreData + Send + Sync + 'static,
{
    store
        .create_data::<D>(name)
        .map(|data| Box::new(data) as ErasedData)
}

fn open<D>(store: &Store, name: &str) -> Result<ErasedData, StoreError>
where
    D: StoreData + Send + Sync + 'static,
{
    store
        .open_data::<D>(name)
        .map(|data| Box::new(data) as ErasedData)
}

/// Failure while assembling typed operation data.
#[derive(Debug, Error, Eq, PartialEq)]
#[non_exhaustive]
pub enum MaterializeError {
    /// A logical resource appears more than once in a schema or instance set.
    #[error("operation data {name:?} appears more than once")]
    DuplicateData {
        /// Stable logical resource name.
        name: &'static str,
    },
    /// The definition requested a logical resource absent from the instance set.
    #[error("operation data {name:?} was not provided")]
    MissingData {
        /// Stable logical resource name.
        name: &'static str,
    },
    /// The definition requested a resource using a different typed data class.
    #[error("operation data {name:?} has the wrong data class")]
    WrongDataClass {
        /// Stable logical resource name.
        name: &'static str,
    },
    /// The definition did not consume one of its declared logical resources.
    #[error("operation data {name:?} was not consumed")]
    UnexpectedData {
        /// Stable logical resource name.
        name: &'static str,
    },
}

/// Failure while binding one Operation definition to exact logical Schemas.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum OperationBindError {
    /// The supplied Schema count differs from the Definition's input arity.
    #[error("operation requires {expected} input schemas but received {actual}")]
    InputCount {
        /// Number of ordered input Schemas required by the Definition.
        expected: usize,
        /// Number of ordered input Schemas supplied by the caller.
        actual: usize,
    },
    /// One supplied logical input Schema violates the Change Schema contract.
    #[error("operation input schema {input} is invalid: {source}")]
    InvalidInputSchema {
        /// Zero-based input port containing the invalid Schema.
        input: usize,
        /// Concrete logical Schema validation failure.
        #[source]
        source: SchemaError,
    },
    /// The concrete Operation rejected otherwise valid ordered input Schemas.
    #[error("operation rejected its input schemas: {source}")]
    Rejected {
        /// Operation-specific structured Schema failure.
        #[source]
        source: OperationSchemaError,
    },
    /// A Source or Transform failed to bind its required output Schema.
    #[error("operation kind requires an output schema but its binding has none")]
    MissingOutput,
    /// A Sink binding incorrectly declared an output Schema.
    #[error("outputless operation kind bound an output schema")]
    UnexpectedOutput,
    /// The bound logical output Schema violates the Change Schema contract.
    #[error("operation output schema is invalid: {source}")]
    InvalidOutputSchema {
        /// Concrete logical Schema validation failure.
        #[source]
        source: SchemaError,
    },
}
