use std::{any::Any, collections::BTreeMap, fmt::Debug, marker::PhantomData};

use dogpaddle_store::{Store, StoreData, StoreError};
use thiserror::Error;

use crate::operation::Operation;

mod private {
    pub trait Sealed {}
}

pub(crate) use private::Sealed;

type ErasedData = Box<dyn Any + Send + Sync>;
type CreateFn = fn(&mut Store, &str) -> Result<ErasedData, StoreError>;
type OpenFn = fn(&Store, &str) -> Result<ErasedData, StoreError>;

/// One stable logical data name paired with its erased typed data class.
///
/// Concrete operation modules declare these values statically. Flow calls the
/// embedded typed `create` or `open` function without enumerating operations or
/// Store collection types.
#[doc(hidden)]
#[derive(Clone, Copy)]
pub struct DataDeclaration {
    name: &'static str,
    create: CreateFn,
    open: OpenFn,
}

/// Named typed data objects created or opened by Flow for one operation.
///
/// Values are erased only while crossing the object-safe definition boundary.
/// A concrete definition consumes them with the typed names generated by its
/// declaration, and the runtime operation stores only concrete collections.
#[doc(hidden)]
pub struct DataInstances {
    remaining: BTreeMap<&'static str, ErasedData>,
}

/// One typed logical data name used by a concrete definition.
pub(crate) struct DataName<D> {
    declaration: DataDeclaration,
    _data: PhantomData<fn() -> D>,
}

/// Pure definition shared by every built-in operation.
///
/// The trait is sealed: the persistent operation set is closed inside this
/// crate. Flow creates or opens the declared data objects before asking the
/// definition to assemble its runtime [`Operation`].
pub trait OperationDefinition: private::Sealed + Debug + Send + Sync + 'static {
    /// Returns the exact number of ordered upstream stages this definition accepts.
    fn input_count(&self) -> usize;

    /// Returns whether this operation produces a downstream change stream.
    ///
    /// Flow uses this declaration to decide whether the owning stage has an
    /// output log. It is independent of whether the current topology happens
    /// to connect any downstream stages.
    fn produces_output(&self) -> bool;

    /// Returns the operation's stable logical data names and typed classes.
    ///
    /// Flow prefixes each name with the owning stage's stable resource path.
    /// Names, collection types, codecs, and any applicable size choices form
    /// part of the operation's persistent schema. The returned slice has
    /// deterministic declaration order, while materialization binds instances
    /// by name.
    #[doc(hidden)]
    fn data(&self) -> &'static [DataDeclaration];

    /// Assembles a runtime operation from named typed data instances.
    ///
    /// # Errors
    ///
    /// Returns [`MaterializeError`] when the supplied instances do not match
    /// the definition's declared data schema.
    #[doc(hidden)]
    fn materialize(&self, data: &mut DataInstances)
    -> Result<Box<dyn Operation>, MaterializeError>;

    /// Returns this definition's stable persistent tag.
    #[doc(hidden)]
    fn persistence_tag(&self) -> u16;

    /// Appends this definition's variant-specific persistent payload.
    #[doc(hidden)]
    fn encode_payload(&self, output: &mut Vec<u8>);
}

impl DataDeclaration {
    /// Returns the stable logical resource name.
    #[doc(hidden)]
    #[must_use]
    pub const fn name(&self) -> &'static str {
        self.name
    }

    /// Creates this declaration's concrete data object.
    ///
    /// # Errors
    ///
    /// Returns a Store error when the physical resource cannot be created.
    #[doc(hidden)]
    pub fn create(
        &self,
        store: &mut Store,
        physical_name: &str,
    ) -> Result<DataInstance, StoreError> {
        (self.create)(store, physical_name).map(|data| DataInstance {
            name: self.name,
            data,
        })
    }

    /// Opens this declaration's concrete data object.
    ///
    /// # Errors
    ///
    /// Returns a Store error when the physical resource is missing, has the
    /// wrong placement, or cannot be opened.
    #[doc(hidden)]
    pub fn open(&self, store: &Store, physical_name: &str) -> Result<DataInstance, StoreError> {
        (self.open)(store, physical_name).map(|data| DataInstance {
            name: self.name,
            data,
        })
    }
}

/// One erased data instance carrying its stable logical name.
#[doc(hidden)]
pub struct DataInstance {
    name: &'static str,
    data: ErasedData,
}

impl DataInstances {
    /// Creates an empty instance map.
    #[doc(hidden)]
    #[must_use]
    pub const fn new() -> Self {
        Self {
            remaining: BTreeMap::new(),
        }
    }

    /// Adds one data object created or opened from a declaration.
    ///
    /// # Errors
    ///
    /// Returns [`MaterializeError::DuplicateData`] when the name is already present.
    #[doc(hidden)]
    pub fn insert(&mut self, instance: DataInstance) -> Result<(), MaterializeError> {
        if self.remaining.contains_key(instance.name) {
            return Err(MaterializeError::DuplicateData {
                name: instance.name,
            });
        }
        self.remaining.insert(instance.name, instance.data);
        Ok(())
    }

    /// Verifies that the operation consumed every provided instance.
    ///
    /// # Errors
    ///
    /// Returns [`MaterializeError::UnexpectedData`] for the first unconsumed name.
    #[doc(hidden)]
    pub fn finish(self) -> Result<(), MaterializeError> {
        self.remaining.into_keys().next().map_or(Ok(()), |name| {
            Err(MaterializeError::UnexpectedData { name })
        })
    }

    pub(crate) fn take<D>(&mut self, name: &DataName<D>) -> Result<D, MaterializeError>
    where
        D: StoreData + Send + Sync + 'static,
    {
        let logical_name = name.declaration.name;
        let erased = self
            .remaining
            .remove(logical_name)
            .ok_or(MaterializeError::MissingData { name: logical_name })?;
        erased
            .downcast::<D>()
            .map(|data| *data)
            .map_err(|_| MaterializeError::WrongDataClass { name: logical_name })
    }
}

impl<D> DataName<D>
where
    D: StoreData + Send + Sync + 'static,
{
    pub(crate) const fn new(name: &'static str) -> Self {
        Self {
            declaration: DataDeclaration {
                name,
                create: create::<D>,
                open: open::<D>,
            },
            _data: PhantomData,
        }
    }

    pub(crate) const fn declaration(&self) -> DataDeclaration {
        self.declaration
    }
}

fn create<D>(store: &mut Store, name: &str) -> Result<ErasedData, StoreError>
where
    D: StoreData + Send + Sync + 'static,
{
    store
        .create_data::<D>(name)
        .map(|data| Box::new(data) as ErasedData)
}

fn open<D>(store: &Store, name: &str) -> Result<ErasedData, StoreError>
where
    D: StoreData + Send + Sync + 'static,
{
    store
        .open_data::<D>(name)
        .map(|data| Box::new(data) as ErasedData)
}

/// Failure while assembling typed operation data.
#[derive(Debug, Error, Eq, PartialEq)]
#[non_exhaustive]
pub enum MaterializeError {
    /// A logical resource appears more than once in a schema or instance set.
    #[error("operation data {name:?} appears more than once")]
    DuplicateData {
        /// Stable logical resource name.
        name: &'static str,
    },
    /// The definition requested a logical resource absent from the instance set.
    #[error("operation data {name:?} was not provided")]
    MissingData {
        /// Stable logical resource name.
        name: &'static str,
    },
    /// The definition requested a resource using a different typed data class.
    #[error("operation data {name:?} has the wrong data class")]
    WrongDataClass {
        /// Stable logical resource name.
        name: &'static str,
    },
    /// The definition did not consume one of its declared logical resources.
    #[error("operation data {name:?} was not consumed")]
    UnexpectedData {
        /// Stable logical resource name.
        name: &'static str,
    },
}
